### ISSUE TITLE
XCode 8.3 Warnings

### ISSUE THREAD

**Issue by TheSwifter** [Skyscanner/SkyFloatingLabelTextField#117]
I just installed the v3.0.0 of SkyFloatingLabelTextField.

But, I get this warning : 
/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextFieldWithIcon.swift:77:103: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

I tried to clean and disintegrate pod and reinstall it, but, it does not work.

I don't want to unlock pod source files .

**Comment by k0nserv** [comment]
Hi,

Yup `M_PI` is deprecated in 8.3. This was fixed in https://github.com/Skyscanner/SkyFloatingLabelTextField/pull/116 by @z3bi, but I haven't released a new verison with this change yet. However you should still be able to build as this is only a warning, you can silence all warnings from all pods with 

```ruby
inhibit_all_warnings!
```

in your `Podfile` or you can silence only warnings from `SkyFloatingLabelTextField` with

```ruby
pod 'SkyFloatingLabelTextField', '~> 3.0.0', inhibit_warnings: true
```

I'll release 3.0.1 after checking that there are no other changes required for Xcode 8.3
