### ISSUE TITLE
How to add custom image instead of unicode?

### ISSUE THREAD

**Issue by Bathibabu** [Skyscanner/SkyFloatingLabelTextField#146]
I am trying to add custom image how can i add?

**Comment by k0nserv** [comment]
No not out of the box. You can achieve it via subclassing though. Have a look at https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/SkyFloatingLabelTextField/SkyFloatingLabelTextFieldExample/Example4/IconTextField.swift and adapt it to use a `UIImageView` instead of a `UILabel` for the icon

**Comment by PedroAnibarro1** [comment]
I did a PR to support images. Just set the icon type to image and set the image. 

PR: #159
