### ISSUE TITLE
How to get the content of floating title in SkyFloatingLabelTextField using XCUITest?

### ISSUE THREAD

**Issue by ksadowski** [Skyscanner/SkyFloatingLabelTextField#184]
Hello,

I've already posted this question on Stack Overflow as instructed (https://stackoverflow.com/questions/46937080/how-to-get-the-content-of-floating-title-in-skyfloatinglabeltextfield-using-xcui) but unfortunately didn't get any response and it's still blocking my tests.

Can anybody help me with such issue? Below you can find original Stack Overflow question:

> In my XCUITests I need to check content of floating title label in SkyFloatingLabelTextField after validation error.
> 
> I've set accessibilityIdentifier for SkyFloatingLabelTextField element, so I can tap and enter text into it without any issue, but how can I access its title (titleLabel?) using only XCUIElement?
> 
> I tried to set titleLabel as accessibilityElement with its own accessibilityIdentifier, but I wasn't able to access the text field in my tests after that.

**Comment by k0nserv** [comment]
I have very little experience with XCUITest and no experience with XCUITest for `SkyFloatingLabelTextField` unfortunately. `SkyFloatingLabelTextField` inherits from `UITextField` so if you google for this but use `UITextField` instead of `SkyFloatingLabelTextField` any answer you find should be applicable to both.

**Comment by k0nserv** [comment]
cc @bogren

**Comment by dennytwix** [comment]
Hi @ksadowski 

The problem is that `titleLabel` is a child of `textField` and they both have accessibility enabled, so `titleLabel` is not accessible in this case. 
There is a workaround if you use accessibility only for UI tests – to disable accessibility for `textField`:
```
textField.isAccessibilityElement = false
textField.accessibilityIdentifier = "test-field"

textField.titleLabel.isAccessibilityElement = true
textField.titleLabel.accessibilityIdentifier = "test-field-title"
```

Later in UI tests you can access both of them:
```
let testField = elementsQuery.textFields["test-field"]
let testFieldTitle = testField.staticTexts["test-field-title"]
```
