### ISSUE TITLE
Selected title shows up very time when user touches text field

### ISSUE THREAD

**Issue by amanbolat** [Skyscanner/SkyFloatingLabelTextField#39]
When i implemented SkyFloatingLabelTextField to my project it doesn't work correct. Every time when i tap text field `Selected Title` will show up. Also in the examples there is only one Example 0 doesn't show selected title on tap, but others ones do.

**Comment by intonarumori** [comment]
I can confirm that when textfield is selected the title first animates in the immediately animates out.
To reproduce you can use following setup in the first example:

![simulator screen shot 02 may 2016 14 15 03](https://cloud.githubusercontent.com/assets/86030/14954163/7311d15a-1070-11e6-8df0-c2a15eca9237.png)

**Comment by gergelyorosz** [comment]
Thanks for both reports. I've started to look into this and am working on a fix. It seems the root of the issue is that in the current implementation there's a `titleVisible` property and an `isTitleVisible()` method - that sometimes return different values. 

Also, when `highlighted` is set to true, the title is shown for a short while. I thinks this latter behaviour might cause the issue. I'm still investigating, and looking for a fix that would make the control more straightworward (both for the implementation, and the API).

Hopefully I'll have a proposed fix in 1 or 2 days.

**Comment by danlozano** [comment]
I did have this problem with version 1.1.1, ironically after updating to version 1.2.0 (which was meant to fix this problem, that I personally did not have) now I DO have the problem 🤔, weird.

Downgraded back to 1.1.1 and I no longer have the title flashing problem.

**Comment by gergelyorosz** [comment]
@danlozano thanks for the report. We've just very recently fixed this, and I've created a new release, v1.2.1. If you upgrade to this one, this bug should no longer be present.

**Comment by danlozano** [comment]
Awesome! Thanks for the great POD 👍
